version: 2.1

jobs:
  deploy-infrastructure:
    docker:
      - image: circleci/node:12.10
    parameters:
      stage_name:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "workspace/package-lock.json" }}
            - dependencies-cache
      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless

      - run:
          name: Install dependencies
          command: (cd workspace && npm install)

      - run:
          name: Deploy application
          command: |
            cd workspace
            serverless deploy -s << parameters.stage_name >>

      - save_cache:
          paths:
            - node_modules
            - workspace/node_modules
          key: dependencies-cache-{{ checksum "workspace/package-lock.json" }}


  deploy-service:
    docker:
      - image: circleci/node:12.10
    parallelism: 3
    parameters:
      service_path:
        type: string
      stage_name:
        type: string
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "workspace/package-lock.json" }}
            - dependencies-cache

      - run:
          name: Install Serverless CLI
          command: sudo npm i -g serverless

      - run:
          name: Install dependencies
          command: |
            npm install
            cd << parameters.service_path >>
            npm install

      - run:
          name: Deploy application
          command: |
            cd << parameters.service_path >>
            serverless deploy -s << parameters.stage_name >>

      - save_cache:
          paths:
            - node_modules
            - << parameters.service_path >>/node_modules
          key: dependencies-cache-{{ checksum "workspace/package-lock.json" }}

workflows:
  build-deploy:
    jobs:
      # non-master branches deploys to stage named by the branch
      - deploy-infrastructure:
          name: Deploy Infrastructure
          stage_name: ${CIRCLE_BRANCH}
          context: WeCo-Development
          filters:
            branches:
              only:
                - dev
                - qa

      - deploy-service:
          name: Deploy API
          service_path: workspace/apps/api
          stage_name: ${CIRCLE_BRANCH}
          context: WeCo-Development
          requires:
            - deploy-infrastructure
          filters:
            branches:
              only:
                - dev
                - qa

      # master branch deploys to the 'prod' stage
#      - deploy-service:
#          name: Deploy Users API
#          service_path: services/users-api
#          stage_name: prod
#          context: Production
#          filters:
#            branches:
#              only: master
#
#      - deploy-service:
#          name: Deploy Posts API
#          service_path: services/posts-api
#          stage_name: prod
#          context: Production
#          filters:
#            branches:
#              only: master
#
#      - deploy-service:
#          name: Deploy Cron Job
#          service_path: services/cron-job
#          stage_name: prod
#          context: Production
#          filters:
#            branches:
#              only: master
