jobs:
  deploy-infrastructure:
    executor: serverless/default
    steps:
      - checkout
      - aws-cli/setup
      - serverless/setup:
          app-name: weco-edu-api
          org-name: wecoedudev
      - run:
          command: serverless deploy -v
          name: deploy-infrastructure
  deploy-api:
    executor: serverless/default
    steps:
      - serverless/setup:
          app-name: weco-edu-api
          org-name: wecoedudev
      - run:
          command: (cd apps/api && serverless deploy -v)
          name: deploy-api
orbs:
  aws-cli: circleci/aws-cli@1.1.0
  node: circleci/node@1.1.6
  serverless-framework: circleci/serverless-framework@1.0.1
version: 2.1
workflows:
  deploy:
    jobs:
      - node/test:
          version: 13.11.0
      - deploy-infrastructure:
          requires:
            - node/test
      - deploy-api:
          requires:
            - deploy-infrastructure