# app and org for use with dashboard.serverless.com
org: wecoedudev
app: weco-edu-api

service: infrastructure
plugins:
  localPath: './serverless/plugins'
  modules:
    - serverless-layers

custom:
  workspacePath: './'
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, "${self:custom.config.region}", 'ca-central-1'}
  config: ${file(./serverless/config/${self:custom.stage}.json)}
  ACCOUNT_ID: ${self:custom.config.account_id}
  VAR: ${file(${self:custom.workspacePath}/serverless/var.yml)}
  serverless-layers:
    - common:
        dependenciesPath: ./package.json

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  deploymentBucket:
    name: ${self:custom.VAR.s3.deploymentBucket}
  environment: ${file(${self:custom.workspacePath}/serverless/environment.yml)}

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**
#functions:
#  - ${file(./apps/api/functions.yml)}

resources:
  # Cognito
  - ${file(serverless/resources/cognito-user-pool.yml)}
